### Data: Training and Test Sets

Let's imaging your task to predict sale price of the car and your car price depends on some variables (called dependent variable) i.e. Milage and age of the car. So let's say we have 20 cars data and their prices, 80% of data is now Training data which have applied our model (i.e. regression model) and 20% of data is test data i.e. has test predicted ($\hat{y}$) values of the cars to match how close from actual values ($y$)

### Feature Scaling

Feature scaling is always applied to columns and cannot applied across the columns (rows). There are multiple techiniques and among them there are two:

1. Normalization: Take the min value of a column and substracting it from each value and then dividing by (maximum - min values) of column. This way you will get adjusted columns values between 0 or 1

    ### $X^{'}=\frac{X-X_{min}}{X_{max}-X_{min}}$

2. Standardization: Process is similar, but instead of substracting by minumum, we substract by average and divide by standard daviation and column values generally between -3 and +3

    ### $X^{'}=\frac{X-\mu}{\sigma}$

    Let's see example by some data here

In [ ]:
import pandas as pd

In [10]:
data = {"Person":["Person1","Person2","Person3"],
        "Salary":[70000,60000,52000],
        "Age":[45,44,40]
        }


df = pd.DataFrame(data)
df.head()

    Person  Salary  Age
0  Person1   70000   45
1  Person2   60000   44
2  Person3   52000   40

So if you see the salary and age columns, those columns data difference are lot more than each other (salary & age) where salary differece is respectively 10000 and 8000 and age different is 1 and 4 which has very different data than each other because of their nature. So we might get on the consclusion and focus only large numbers and leave small number as they don't look important. So if there is not comparable then we use normalization on data.

In [13]:
min_sal = df["Salary"].min()
max_sal = df["Salary"].max()

min_age = df["Age"].min()
max_age = df["Age"].max()

salaries = [(x - min_sal) / (max_sal - min_sal) for x in df["Salary"]]
ages = [(x - min_age) / (max_age - min_age) for x in df["Age"]]

df["Normalized Salary"] = salaries
df["Normalized Age"] = ages

df.head()

    Person  Salary  Age  Normalized Salary  Normalized Age
0  Person1   70000   45           1.000000             1.0
1  Person2   60000   44           0.444444             0.8
2  Person3   52000   40           0.000000             0.0